name: Deploy Jobs

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy-glue:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy Ingest Lambda
        working-directory: ingest
        run: |
          chmod +x deploy.sh
          ./deploy.sh wistia_to_s3

      - name: Deploy CommitCheckpoint Lambda
        working-directory: ingest
        run: |
          ./deploy.sh wistia_commit_checkpoint

      - name: Upload Glue job scripts to S3
        run: |
          aws s3 cp jobs/run.py s3://jl-wistia-pipeline/jobs/scripts/run.py
          aws s3 cp jobs/config.py s3://jl-wistia-pipeline/jobs/libs/config.py
          aws s3 cp jobs/main.py s3://jl-wistia-pipeline/jobs/libs/main.py
